# Generated by Django 4.2.11 on 2024-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
