# Generated by Django 4.2.11 on 2024-04-17 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='alertTime',
            new_name='alertStartTime',
        ),
        migrations.AddField(
            model_name='alerts',
            name='alertEndTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
