# Generated by Django 4.2.11 on 2024-04-17 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_alerttime_alerts_alertstarttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='motionId',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
