# Generated by Django 4.2.11 on 2024-04-17 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alerts_motionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='alertDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
