# Generated by Django 4.2.11 on 2024-04-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_alerts_alertendtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='motionId',
        ),
    ]
